Light work on database
Johannes253/FaulknerCountyJuvenileCourt pull request #11
Opened 2023-11-15 07:16 UTC by justingrubbs

Manually scaffolded pages, fixed Juvenile page, fixed Crime page, added ugly Tables page that links to other tables

2023-11-15 20:24 UTC, Johannes253 commented
Can you change the datatype of ID to string please? Also the tables, offences, school etc should only be accessible while logged in, please change that aswell.

2023-11-15 20:24 UTC, Johannes253 requested changes
Can you change the datatype of ID to string please? Also the tables, offences, school etc should only be accessible while logged in, please change that aswell.

2023-11-17 19:59 UTC, HaydenMoussa approved these changes
looks good

2023-11-17 19:59 UTC, HaydenMoussa approved these changes

2023-11-17 21:08 UTC, merged